### ISSUE TITLE
ModPack

### ISSUE THREAD

**Issue by INFERNOUX** [TheRealZeher/DimensionalPocketsII#17]
i didnt read into the crash too much but it feels like its an issue with thaumcraft, heres my full crash report

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5 (1).jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 9/8/18 9:44 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateVegetation(ThaumcraftWorldGenerator.java:219)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:340)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:68)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:56)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:978)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateVegetation(ThaumcraftWorldGenerator.java:219)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:340)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:68)
	at thaumcraft.common.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:56)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:978)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['INFERNOUX'/21151, l='world', x=7.50, y=2.00, z=7.50]]
	Chunk stats: ServerChunkCache: 7 Drop: 0
	Level seed: 969794163
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.103-xxxx-std-ipv6-64
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3777485552 bytes (3602 MB) / 5559549952 bytes (5302 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -Xmx12288M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                | Version                  | Source                                                | Signature                                |
	|:--------- |:--------------------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                   | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                     | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                | custom.jar                                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.4.2759             | custom.jar                                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | openmodscore                      | 0.11.5                   | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | guideapi                          | 1.12-2.1.7-62            | Guide-API-1.12-2.1.7-62.jar                           | None                                     |
	| UCHIJAAAA | bloodmagic                        | 1.12.2-2.3.3-101         | BloodMagic-1.12.2-2.3.3-101.jar                       | None                                     |
	| UCHIJAAAA | animus                            | 1                        | Animus-2.0.3.jar                                      | None                                     |
	| UCHIJAAAA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                                | None                                     |
	| UCHIJAAAA | betterbuilderswands               | 0.12.0                   | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar       | None                                     |
	| UCHIJAAAA | thaumcraft                        | 6.1.BETA24               | Thaumcraft-1.12.2-6.1.BETA24.jar                      | None                                     |
	| UCHIJAAAA | botania                           | r1.10-356                | Botania+r1.10-356.jar                                 | None                                     |
	| UCHIJAAAA | buildcraftlib                     | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | buildcraftcore                    | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | buildcraftbuilders                | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | buildcraftenergy                  | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | buildcraftfactory                 | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | buildcraftrobotics                | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | buildcrafttransport               | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | buildcraftsilicon                 | 7.99.17                  | buildcraft-7.99.17.jar                                | None                                     |
	| UCHIJAAAA | forestry                          | 5.8.1.339                | forestry_1.12.2-5.8.1.339.jar                         | None                                     |
	| UCHIJAAAA | careerbees                        | 1.0                      | careerbees-0.4.0 (1).jar                              | None                                     |
	| UCHIJAAAA | codechickenlib                    | 3.2.1.351                | CodeChickenLib-1.12.2-3.2.1.351-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks                     | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal (1).jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | computercraft                     | 1.80pr1                  | ComputerCraft1.80pr1.jar                              | None                                     |
	| UCHIJAAAA | creeperconfetti                   | 1.4.2                    | creeperconfetti-1.4.2.jar                             | None                                     |
	| UCHIJAAAA | cucumber                          | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                             | None                                     |
	| UCHIJAAAA | trzlib                            | 2.1.18                   | trzlib-1.12.2-1.2.18-universal.jar                    | None                                     |
	| UCHIJAAAA | dimensionalpocketsii              | 1.2.14-beta              | dimensionalpocketsii-1.12.2-1.2.14-beta-universal.jar | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.37            | EnderCore-1.12.2-0.5.37.jar                           | None                                     |
	| UCHIJAAAA | enderio                           | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | ftblib                            | 5.3.0.42                 | FTBLib-5.3.0.42.jar                                   | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.31                   | EnderIO-1.12.2-5.0.31.jar                             | None                                     |
	| UCHIJAAAA | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | energyconverters                  | 1.0.1.2                  | energyconverters_1.12.1-1.0.1.2.jar                   | None                                     |
	| UCHIJAAAA | extrautils2                       | 1.0                      | extrautils2-1.12-1.8.5.jar                            | None                                     |
	| UCHIJAAAA | forgelin                          | 1.7.4                    | Forgelin-1.7.4.jar                                    | None                                     |
	| UCHIJAAAA | forgemultipartcbe                 | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe                     | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar          | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe             | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar          | None                                     |
	| UCHIJAAAA | harvest                           | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                             | None                                     |
	| UCHIJAAAA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest                         | 1.12.2-7.0.46.831        | ironchest-1.12.2-7.0.46.831.jar                       | None                                     |
	| UCHIJAAAA | magicbees                         | 1.0                      | MagicBees-1.12.2-3.1.10.jar                           | None                                     |
	| UCHIJAAAA | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | mekanism                          | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                        | None                                     |
	| UCHIJAAAA | mysticalagriculture               | 1.6.13                   | MysticalAgriculture-1.12-1.6.13.jar                   | None                                     |
	| UCHIJAAAA | openmods                          | 0.11.5                   | OpenModsLib-1.12.2-0.11.5 (1).jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks                        | 1.7.6                    | OpenBlocks-1.12.2-1.7.6 (1).jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | harvestcraft                      | 1.12.2y                  | Pam's+HarvestCraft+1.12.2y.jar                        | None                                     |
	| UCHIJAAAA | radixcore                         | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar                  | None                                     |
	| UCHIJAAAA | tcinventoryscan                   | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar            | None                                     |
	| UCHIJAAAA | yabba                             | 1.1.2.25                 | YABBA-1.1.2.25.jar                                    | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5 (1).jar)
  openmods.core.OpenModsClassTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 240; [EntityPlayerMP['INFERNOUX'/21151, l='world', x=7.50, y=2.00, z=7.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by TheRealZeher** [comment]
Incorrect Biome Setup.
