### ISSUE TITLE
Mod Crash on first "Shift Click" 

### ISSUE THREAD

**Issue by deathbows2me** [TheRealZeher/DimensionalPocketsII#18]
I clicked the block with a "ctrl + right click" since my crouch is ctrl not shift. Instant crash. IThis was a fresh world that I was testing mods on. I was in creative mod when I tried it.

I cannot access that world now. 

Sucks I was planning on using this on my server. I cant wait for it to be more stable and finished.

I would only add groups or something where a clan can access it if they are on a list that the portal owner can change. Maybe this is a function. IDK haha was gonna check it out but  yeahhhhh. haha.

Crash reports and mod list below. Thanks for making mods for MC! I hope this helps with your mod.

[crash-2018-10-29_20.29.30-server.txt](https://github.com/TheRealZeher/DimensionalPockets-II/files/2527545/crash-2018-10-29_20.29.30-server.txt)

[crash-2018-10-29_20.34.13-server.txt](https://github.com/TheRealZeher/DimensionalPockets-II/files/2527546/crash-2018-10-29_20.34.13-server.txt)

![mod list](https://user-images.githubusercontent.com/44592247/47688172-6e8e0000-dbba-11e8-8b83-4c7f00bd7a3d.PNG)

Made a new world and tested it again. Same thing happened heres the crash log. It gets to the "Entering dimension and hangs up. Again in creative mode.

[crash-2018-10-29_20.49.39-server.txt](https://github.com/TheRealZeher/DimensionalPockets-II/files/2527573/crash-2018-10-29_20.49.39-server.txt)

**Comment by TheRealZeher** [comment]
Thanks for bringing this to my attention. I will be back coding soon so once i get set-up again i will take a look at all the bugs currently open. TheRealZeher

**Comment by TheRealZeher** [comment]
This issue should be resolved as at the time the Biome was not correctly set up. If you could test this again (if you are using the same mods) to see if the bug still exists. Cheers! 
-TheRealZeher
