### ISSUE TITLE
Thaumcraft

### ISSUE THREAD

**Issue by stasalcatraz** [TheRealZeher/DimensionalPocketsII#19]
First time i collect all dimensional ore for making cube/ After entering it game crushes. Next time i've added cube by JEI. First time i've entered cube ok. But after some traveling i've try to enter cube and game crushes again. 
[crash-2018-12-23_01.20.11-server.txt](https://github.com/TheRealZeher/DimensionalPockets-II/files/2705621/crash-2018-12-23_01.20.11-server.txt)

**Comment by TheRealZeher** [comment]
Issue is similar to others reported. Incorrect biome setup was the problem.
