### ISSUE TITLE
Mod crashes upon entering the Nether

### ISSUE THREAD

**Issue by OvineWitch** [TheRealZeher/DimensionalPocketsII#31]
I'm using DMII for 1.12.2 with the latest version (3.1.34), same for ZeherlibII (4.1.24).
I'm not sure what's the difference between server and client??? it's a solo world
here's the vanilla fix crash report: https://paste.dimdev.org/ipemakujar.mccrash
(all my mods are also in the report i have a lot of them)
so yeah now i can't access my world at all because spending more than 0.3 seconds crashes it and i am  very sad
I tested again on a flat world in creative and the same thing happens.
50% of the time vanilla fix the cause is unknown but the other 50% it says it's DMII so i thought i'd report it to you

**Comment by TheRealZeher** [comment]
Hi there, I'm sorry you have experienced issues using my mod. I cannot see that bug report, as the server for dimdev is currently down. If you could either use pastebin or put the report here I can certainly look into the issue for you.

-TheRealZeher

**Comment by TheRealZeher** [comment]
I have tested this issue. Entering the nether and placing / using a pocket in the nether is completely possible. If this issue resurfaces i will reopen this issue and update from there.
