### ISSUE TITLE
Respawn Mechanic

### ISSUE THREAD

**Issue by Neubenutzer** [TheRealZeher/DimensionalPocketsII#32]
Sleeping in the pocket dimension should respawn you next to your bed even if you die in the overworld and if you did not sleep and die in the Pocket Dimension you should not respawn in the void and die again, because it is really annoying to get into creative and fly out. By the way you could maybe use code from this mod: [Nomadic Tents](https://www.curseforge.com/minecraft/mc-mods/nomadic-tents)

**Comment by TheRealZeher** [comment]
Issue has been fixed. Sleeping in the bed and using the /kill command spawns you inside the pocket. This will not work if you fall into the void in the end dimension.
