### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by rechalow** [TheRealZeher/DimensionalPocketsII#33]
Can you make a unique discord server
We may all need to discuss relevant topics at any time.
I am a Chinese
And this mod doesn't have Chinese
So open up a Lang of mod

Google translation
I don't know if I can make you understand

**Comment by rechalow** [comment]
By the way, I love this mod
Can you keep this mod going

**Comment by TheRealZeher** [comment]
Hi,

Thanks for leaving the comment. I will look into setting up a discord server for the mod, however i lost access to my discord account so will have to make a new one. Right now i'm very busy with personal things so am finding it hard to code alongside those things. Once I get back to coding I will ensure to make that discord. Thanks for the kind comment, i'm glad you like the mod!

-TheRealZeher

**Comment by rechalow** [comment]
I submitted the Chinese translation, please check. I'd like to do the Chinese publicity of mod for you

**Comment by rechalow** [comment]
Sorry, I just found the Lang file

**Comment by TheRealZeher** [comment]
Sure thing, I would love to have you as part of the team. Upload the Lang file for me and I will add that to the next release of the mod. I have also added you as a collaborator of the project here on discord.

**Comment by TheRealZeher** [comment]
Discord is now live! https://discord.gg/8ydCtzm

**Comment by TheRealZeher** [comment]
@rechalow We now have a discord server - https://discord.gg/8ydCtzm
