### ISSUE TITLE
Question: Modpack allowed?

### ISSUE THREAD

**Issue by Neubenutzer** [TheRealZeher/DimensionalPocketsII#36]
I want to know, if I can use this mod in my modpack, 
because your license doesn't say it clearly.
I hope to get an answer soon.

**Comment by Neubenutzer** [comment]
same goes for zeherlib

**Comment by TheRealZeher** [comment]
Yes of course you can use my mod in your modpack, as long as it is private. If it is public then there are requirements, such as linking to the modpage and ensuring I am named as the author.

**Comment by Neubenutzer** [comment]
Thanks for the fast answer I really love this mod.
Also I was going to link to you even in my private modpack.

**Comment by TheRealZeher** [comment]
Not a problem. Glad you like the mod!
