### ISSUE TITLE
Incompatibility with Betterportals

### ISSUE THREAD

**Issue by Neubenutzer** [TheRealZeher/DimensionalPocketsII#38]
on the previous version it worked perfectly fine, but now it doesn't load the chunks (in f3 it says "waiting for chunk...")
[betterportals](https://www.curseforge.com/minecraft/mc-mods/betterportals)

**Comment by TheRealZeher** [comment]
Hi, could you please provide the following information for me to be able to investigate:

Minecraft Version. [Ex: 1.12.2]
Mod version. [Ex: 1.1.11]
ZeherLibII Version. [Ex: 1.1.11]
Full crash report. [Which includes a full list of mods being run & the version of forge you are running]
Whether you where running it on a server, or a client.

Once provided I will take a look into the problem.

**Comment by TheRealZeher** [comment]
Issue was solved with BetterPortals specific code.
