### ISSUE TITLE
Server Side - Crash 1.12.2 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheRealZeher/DimensionalPocketsII#42]
https://gist.github.com/P3rf3ctXZer0/67a2b8080447d066f9c34bd5f7ca2b02

**Comment by TheRealZeher** [comment]
Issue fixed in release 5.2.80-beta

**Comment by P3rf3ctXZer0** [comment]
Let me know when it was released.

**Comment by TheRealZeher** [comment]
It has been released, sorry for late reply I've been busy.
