### ISSUE TITLE
Client Side Kick While on Server - When using pocket interface 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheRealZeher/DimensionalPocketsII#43]
Strange client side crash! https://gist.github.com/P3rf3ctXZer0/c664283aacb1f2849df345fbe32239f2

![O7QdmbL 1](https://user-images.githubusercontent.com/10351221/88844192-eaf6ae00-d1a7-11ea-875a-196ac57613d2.png)

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/e9259f7b4720498e54eb8803e39f06b8

**Comment by TheRealZeher** [comment]
I will take a look into the problem when I get home 👍

**Comment by TheRealZeher** [comment]
Reverted back to old packet method, error still occurs. This will take some time to debug.

**Comment by P3rf3ctXZer0** [comment]
I will ignore interface for now and warn users.

**Comment by TheRealZeher** [comment]
Okay. I will get around to fixing it, I am just focusing on the 1.14.4 port

**Comment by P3rf3ctXZer0** [comment]
Ah you should wait till 1.16.X is final since pixelmon and a few other big players are waiting. If you don't mind me asking why 1.14.4?

**Comment by TheRealZeher** [comment]
I will go to 1.16.1 when forge is ready, 1.14.4 seemed logical. I may go for 1.15.2 in the mean time but I'm not sure

**Comment by P3rf3ctXZer0** [comment]
https://minecraft.gamepedia.com/Java_Edition_20w14%E2%88%9E

**Comment by TheRealZeher** [comment]
When 1.16.x is ready I will update to it. Right now Forge doesn't even have de-obfuscated methods yet

**Comment by P3rf3ctXZer0** [comment]
Okay well hope I can help with 1.12.2 development. Gonna play now - good luck.
If you want hands on experience "https://www.curseforge.com/minecraft/modpacks/pixelmon-evolved"

**Comment by TheRealZeher** [comment]
That would be much appreciated! Glad you like the mod by the way. Have you joined the Discord? I post updates there and there are channels for discussing bugs. Would make it very easy to communicate with you when fixing bugs.

**Comment by P3rf3ctXZer0** [comment]
joined
